services:
  postgres:
    container_name: rest_postres_api_postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rest_postres_api_postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql
