services:
  postgres:
    container_name: rest-postgres-api
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rest-postgres-api
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql
